version: "3.9"

services:

  download_bank:
    build: download
    working_dir: /data
    volumes:
      - ./data:/data
    command: [ "http://37.139.43.86/bank.csv" ]

  spark_task_1:
    build: spark_task_1
    depends_on:
      download_bank:
        condition: service_completed_successfully
    environment:
      - PYTHONPATH=${PYTHONPATH}:/app/spark_task_1
      - SRC_FILE=data/bank.csv
      - TARGET_FILE=data/bank.parquet
    volumes:
      - ./data:/app/data
      - ./spark_task_1:/app/spark_task_1

  postgresql:
    image: 'bitnami/postgresql:13'
    ports:
      - 5432:5432
    volumes:
      - './services/postgresql:/bitnami/postgresql'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=p_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=postgre
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U p_user"]
      interval: 10s
      timeout: 5s
      retries: 10

  spark_task_2:
    build: spark_task_2
    depends_on:
<<<<<<< HEAD
<<<<<<< HEAD
      spark_task_1:
        condition: service_completed_successfully
=======
>>>>>>> 659fc12 (added healthcheck)
=======
      spark_task_1:
        condition: service_completed_successfully
>>>>>>> 0d9485b (added dependencies to docker-compose)
      postgresql:
        condition: service_healthy
    environment:
      - PYTHONPATH=${PYTHONPATH}:/app/spark_task_2
      - SRC_FILE=data/bank.parquet
      - TARGET_TABLE=public.bank
    volumes:
      - ./data:/app/data
      - ./spark_task_2:/app/spark_task_2
    links:
      - postgresql:postgresql
    logging:
      driver: "json-file"

  age_distr:
    build: age_distr
    depends_on:
      spark_task_2:
        condition: service_completed_successfully
      postgresql:
        condition: service_healthy
    environment:
      - PYTHONPATH=${PYTHONPATH}:/app/age_distr
      - SRC_TABLE=public.bank
      - TARGET_FILE=data/age_distr.csv
    volumes:
      - ./data:/app/data
      - ./age_distr:/app/age_distr
<<<<<<< HEAD
      - ./logs:/app/logs
=======
>>>>>>> 659fc12 (added healthcheck)
    links:
      - postgresql:postgresql